pizzamama/main/urls.py
from django.urls import path
from . import views


app_name = 'main'

urlpatterns = [
    path('', views.index, name="index"),
]

pizzamama/menu/urls.py
from django.urls import path
from . import views


app_name = 'menu'


urlpatterns = [
    path('', views.index, name="index"),
]

pizzamama/pizzamama/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('menu/', include('menu.urls')),
    path('', include('main.urls')),  # main page

]

pizzamama/main/models.py
from django.db import models

# Create your models here.

pizzamama/menu/models.py
from django.db import models


class Pizza(models.Model):
    name = models.CharField(max_length=200)
    ingredients = models.CharField(max_length=400)
    price = models.FloatField(default=0)
    vegetarian = models.BooleanField(default=False)

# Returns the name of the Objects in the DB
    def __str__(self):
        return self.name

pizzamama/main/views.py
from django.shortcuts import render

# Create your views here.


def index(request):
    return render(request, 'main/index.html')

pizzamama/menu/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Pizza


# Create your views here.

def index(request):
    pizzas = Pizza.objects.all().order_by('price')
    pizzas_names_and_price = [pizza.name + " : $ " + str(pizza.price) for pizza in pizzas]
    pizzas_names_str = ", ".join(pizzas_names_and_price)
    # return HttpResponse("Hello there")
    return render(request, 'menu/index.html', {'pizzas': pizzas})

pizzamama/main/templates/main/index.html
{% load static %}

<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Title</title>
	<link rel="stylesheet" href="{% static 'main/style.css' %}">
</head>
<body>

	<div class="mainLogo">
		<img src="{% static 'main/res/img/main_logo.png' %}" alt="Main Logo">

		<!-- Uses namespaces from urls.py file to get the proper link -->
		<a href="{% url 'menu:index' %}">See our menu</a>
	</div>

</body>
</html>

pizzamama/menu/templates/menu/index.html
{% load static %}

<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Our pizzas</title>
	<link rel="stylesheet" href="{% static 'menu/style.css' %}">
</head>
<body>
	
	<div class="mainLogo">
		<a href="{% url 'main:index' %}">

			<img src="{% static 'menu/res/img/small_logo.png' %}" alt="PizzaMama">
		</a>
	</div>
	
	<section class="mainContent">
		<div class="menuTitle">
			<h1>Our Pizzas</h1>
		</div>
		
		<div class="menuList">
			
			{% for pizza in pizzas %}
			
			<div class="menuListItem">
				<span class="menuItemTitle">{{ pizza.name }} </span>
				<span class="menuItemPrice">$ {{ pizza.price }}</span>
				<span class="menuItemIngredients">{{ pizza.ingredients }}</span>
				
				{% if pizza.vegetarian %}
				<span class="menuItemVegetarian">
						VEGETARIAN
				</span>
				{% endif %}
			</div>
			
			{% endfor %}
			
		</div>
		
	</section>
	

</body>
</html>